version: "20.10.17"

services:

  application:
    image: herlios:main
    hostname: herlios.local
    volumes:
      - ./application/src:/var/www/herlios.local/:rw
    ports:
      - "443:443"
    networks:
      - herlios

  db:
    image: mysql:5.7.38-debian
    hostname: db.herlios.local
    ports:
      - "3306:3306"
    volumes:
      - ./database-files:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ASDQWE123
    networks:
      - herlios

  iam:
    image: quay.io/keycloak/keycloak:17.0.1
    hostname: iam.herlios.local
    ports:
      - "8080:8080"
    environment:
      KC_HOSTNAME: iam.herlios.local
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ASDQWE123
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_FEATURES: token-exchange
      KC_DB: mysql
      KC_DB_URL_HOST: db.herlios.local
      KC_DB_USERNAME: iam
      KC_DB_PASSWORD: ASDQWE123
    networks:
      - herlios
    command:
      [
        'start-dev'
      ]

networks:
  herlios:
    driver: bridge
